### ISSUE TITLE
"Not a valid semver version: Varies with device"

### ISSUE THREAD

**Issue by junioroga** [flexible-agency/react-native-check-version#10] opened 2021-02-08 12:01 UTC
My application on the device is with version 1.0.3 exactly the same as the store, but needsUpdate always returns true.

I tried to change the device version to 1.0.4 in an attempt to solve the problem, but needsUpdate still returns true.

![image](https://user-images.githubusercontent.com/7414393/107216555-b2a01a00-69eb-11eb-8e69-477d37eef32e.png)

![image](https://user-images.githubusercontent.com/7414393/107216953-3fe36e80-69ec-11eb-829c-6c6da0dc53c2.png)

**Comment by tschoffelen** [comment] 2021-02-08 12:13
Interesting! Haven't seen that one before. Would you be able to email me the bundle ID so that I can try to reproduce it? thomas at schof.co

**Comment by tschoffelen** [comment] 2021-02-08 12:48
Thanks for your email! Posting this here as well as it might be helpful for others:

> I've had a quick look, and it seems like this happens when there are multiple APKs/bundles in production at the same time: https://stackoverflow.com/a/25463637
> 
> In that case, we can't automatically determine the version available for the current user. I'm not sure if there's a way to work around that, although `needsUpdate` should definitely not be `true` in that case, I'll get that fixed!

**Comment by RichardBoyder** [comment] 2021-02-17 07:40
Hi @tschoffelen With regards to the above. Have you managed a fix? 

Im considering using this plugin and just want to make sure it is foolproof and won't fail as live store releases are a big thing, can't have it happen even once that true is set all the time and users keep seeing a message to update and they have the latest.

Appreciate the plugin and really do hope I can use it.

**Comment by tschoffelen** [comment] 2021-02-17 10:41
Hi @RichardBoyder! Yes, this problem has been resolved. Anything that doesn't look like a version number (ie doesn't have a period in the string), won't result in a `needsUpdate`: true.

https://github.com/flexible-agency/react-native-check-version/commit/6a8d8004205ca93911a94b3d4a826b9ad163fe3a

Still not sure why Google Play is returning 'Varies with device' for this specific bundle though.

**Comment by tschoffelen** [comment] 2021-09-19 10:17
Closing because this problem has been resolved, and the only open question is also addressed in #14.

**Closed by tschoffelen** 2021-09-19 10:17 UTC

**Comment by faizanbuggy** [comment] 2021-09-20 12:34
I am also facing the same issue on iOS.
