### ISSUE TITLE
[android] Invalid time value

### ISSUE THREAD

**Issue by kanghyeok93** [flexible-agency/react-native-check-version#31] opened 2022-05-27 04:40 UTC
Currently, it does not work on Android, so when I take a log, an error like the picture is displayed.

![스크린샷 2022-05-27 오후 1 38 01](https://user-images.githubusercontent.com/38206489/170630139-b18f3a6e-b9de-453c-84c0-293577ec096c.png)

**Comment by nitishkumar325** [comment] 2022-05-27 07:51
same here

**Comment by tschoffelen** [comment] 2022-05-27 13:20
This is caused by the Google Play changes - see #30. Closing as duplicate.

**Closed by tschoffelen** 2022-05-27 13:20 UTC
