### ISSUE TITLE
Invalid time value error

### ISSUE THREAD

**Issue by vu-dang** [flexible-agency/react-native-check-version#28] opened 2022-03-13 17:55 UTC
Hello,

CheckVersion is returning the following error on a Samsung device today:

{"error": "Invalid time value"}

Is this due to daylight saving time change today?

**Comment by kanghyeok93** [comment] 2022-05-27 04:33
i have the same problem

**Comment by tschoffelen** [comment] 2022-05-27 13:20
This is caused by the Google Play changes - see #30. Closing as duplicate.

**Closed by tschoffelen** 2022-05-27 13:20 UTC
